// Playbooks & Scripts — Banco de Conhecimento da Matriz
// Dados estruturados dos PDFs de Performance e Criação

export interface ScriptCard {
  id: string;
  numero: number;
  titulo: string;
  situacao: string;
  objetivo: string;
  oQueClientePrecisaEntender: string;
  scriptCurto: string;
  scriptCompleto: string;
  tomIdeal: string;
  erroAEvitar: string;
}

export interface ManualBloco {
  id: string;
  titulo: string;
  scripts: ScriptCard[];
}

export interface PlaybookSection {
  id: string;
  titulo: string;
  conteudo: string[];
}

export interface PlaybookData {
  playbook: {
    titulo: string;
    subtitulo: string;
    sections: PlaybookSection[];
  };
  manual: {
    titulo: string;
    subtitulo: string;
    blocos: ManualBloco[];
  };
}

// ═══════════════════════════════════════════════
// PERFORMANCE
// ═══════════════════════════════════════════════

export const performanceData: PlaybookData = {
  playbook: {
    titulo: "Playbook Operacional — Performance",
    subtitulo: "Gestor de Performance: onboarding, briefing, estratégia, implantação, otimização, reunião mensal e gestão da estrutura do cliente",
    sections: [
      {
        id: "perf-obj",
        titulo: "1. Objetivo da função",
        conteudo: [
          "O Gestor de Performance é o responsável por desenhar, apresentar, acompanhar e ajustar toda a estrutura estratégica do cliente.",
          "Ele não faz apenas tráfego pago. Ele é o responsável por organizar a jornada completa do cliente dentro do que foi contratado, conectando: copys, social media, criativos, tráfego pago, site/landing page, CRM, relatórios, reuniões de acompanhamento, otimizações e melhorias.",
          "O Gestor de Performance é quem pensa a estrutura, monta a lógica, define a execução estratégica e acompanha o que está funcionando ou não.",
        ],
      },
      {
        id: "perf-entrega",
        titulo: "2. O que a cadeira de Performance entrega",
        conteudo: [
          "A. Onboarding estratégico — recebe o cliente do comercial, entende dores, contexto e contratação, conduz kickoff interno e briefing com cliente.",
          "B. Diagnóstico e coleta de informações — extrai informações estratégicas, entende negócio, oferta, público, histórico, metas e gargalos.",
          "C. Construção da estratégia mensal — cria a estratégia completa, desenha a estrutura de social, tráfego, web e CRM, cria copys e direcionamentos.",
          "D. Apresentação da estratégia — apresenta o plano ao cliente, explica o que será feito, por quê e como, coleta aprovação e feedback.",
          "E. Implantação e estruturação — cria campanhas, organiza CRM, dá início à execução e direciona a criação.",
          "F. Otimização e acompanhamento — analisa resultados, faz ajustes semanais, acompanha números e identifica oportunidades.",
          "G. Renovação estratégica mensal — apresenta números, propõe nova estrutura e reinicia o ciclo.",
        ],
      },
      {
        id: "perf-papel",
        titulo: "3. Papel da Performance dentro da operação",
        conteudo: [
          "O Gestor de Performance é o dono da lógica estratégica do cliente. Ele responde perguntas como: qual a melhor estrutura? Quais canais e campanhas entram? Qual o papel do site e do CRM? Quais conteúdos e criativos são necessários? O que está funcionando? O que precisa ser corrigido?",
          "Ele transforma contrato em estrutura, e estrutura em plano de execução.",
        ],
      },
      {
        id: "perf-contrata",
        titulo: "4. O que o cliente contrata",
        conteudo: [
          "Social media, criativos, tráfego pago, site/landing page, CRM — isoladamente ou em conjunto.",
          "A Performance organiza tudo dentro de uma estrutura única, com lógica estratégica, objetivo e sequência.",
        ],
      },
      {
        id: "perf-principio",
        titulo: "5. Princípio central da função",
        conteudo: [
          "O Gestor de Performance não trabalha por tarefa solta. Ele trabalha por estrutura de resultado.",
          "A copy, o criativo, a campanha, o site e o CRM não existem sozinhos — tudo faz parte de uma mesma estrutura que precisa estar conectada para gerar oportunidade, contato, venda, dados e melhoria contínua.",
        ],
      },
      {
        id: "perf-padrao",
        titulo: "6. O que precisa ser padronizado",
        conteudo: [
          "1. Mesmo fluxo de onboarding",
          "2. Mesmo modelo de briefing",
          "3. Mesmo padrão de coleta de informações",
          "4. Mesmo formato de construção da estratégia",
          "5. Mesmo formato de apresentação da estratégia",
          "6. Mesmo ritmo de otimização semanal",
          "7. Mesmo modelo de reunião mensal",
          "8. Mesmo processo de handoff para Criação",
          "9. Mesmo processo de implantação de campanhas e CRM",
          "10. Mesmo raciocínio de análise e melhoria",
        ],
      },
      {
        id: "perf-visao",
        titulo: "7. Visão geral do processo",
        conteudo: [
          "1. Cliente assina → 2. Kickoff com vendedor → 3. Entrada no WhatsApp → 4. Boas-vindas → 5. Preparação para briefing → 6. Briefing com cliente → 7. Transcrição e organização → 8. Construção da estratégia → 9. Apresentação ao cliente → 10. Aprovação → 11. Implantação de campanhas e CRM → 12. Criação executa criativos, social e site → 13. Acompanhamento diário → 14. Otimização semanal → 15. Nova estratégia do próximo ciclo → 16. Reunião mensal → 17. Reinício do ciclo",
        ],
      },
      {
        id: "perf-etapas",
        titulo: "8–12. Etapas detalhadas",
        conteudo: [
          "Etapa 1 — Kickoff interno com o vendedor: transferir contexto do comercial (o que contratou, principal dor, expectativa, promessa de entrega, urgência, meta).",
          "Etapa 2 — Entrada no WhatsApp e boas-vindas: se apresentar, dar boas-vindas, explicar próximo passo, mostrar importância do briefing.",
          "Etapa 3 — Envio do checklist pré-briefing: acessos Meta/Google/LinkedIn Ads, redes sociais, CRM, informações comerciais, e-mails.",
          "Etapa 4 — Reunião de briefing: alinhar processo, apresentar eKyte, entender contratação, coleta estratégica (negócio, oferta, público, metas, histórico, gargalos, concorrência, processo comercial), verificar acessos.",
          "Etapa 5 — Construção da estratégia: em 48-72h após briefing. Deve cobrir social media, criativos, tráfego pago, web e CRM com lógica e objetivos.",
        ],
      },
      {
        id: "perf-apresentacao",
        titulo: "13–17. Apresentação, aprovação e execução",
        conteudo: [
          "Etapa 6 — Apresentação da estratégia: clara, didática, comercial. Mostrar a lógica, não só entregas. Ouvir feedback e objeções.",
          "Aprovação: copys, conteúdo, criativos, campanhas, web, CRM. A Criação recebe direção para executar.",
          "Regra de calendário: ciclo de 28-30 dias. Próxima reunião com 10-15 dias de antecedência.",
          "Etapa 7 — Handoff para Criação: copys aprovadas, formatos, objetivos, diferenciação social/tráfego, direcionamento de site.",
          "Etapa 8 — Implantação das campanhas: cria campanhas, estrutura públicos, define orçamentos. Campanha reflete a estratégia aprovada.",
          "Etapa 9 — Implantação do CRM: levanta info no briefing, solicita acessos, desenha funil, organiza etapas, mapeia integrações.",
          "Etapa 10 — Relatórios diários: automáticos via eKyte. Coletar e-mails corretos no briefing.",
          "Etapa 11 — Otimização semanal: 1x por semana por cliente. Analisa, ajusta e comunica ao cliente.",
          "Etapa 12 — Reunião mensal: mostrar resultados, ouvir feedback, apresentar aprendizados, propor próximo ciclo.",
        ],
      },
      {
        id: "perf-responsabilidades",
        titulo: "18. Responsabilidades e cronograma",
        conteudo: [
          "A Performance deve: receber cliente, participar do kickoff, conduzir boas-vindas, enviar preparação de briefing, conduzir briefing, gravar e organizar informações, montar inteligência do cliente, construir estratégia completa, apresentar no eKyte, aprovar com cliente, passar briefing para Criação, criar campanhas, organizar CRM, acompanhar relatórios, otimização semanal, reunião mensal, montar próxima estratégia.",
          "A Performance NÃO deve: trabalhar sem entender o que foi vendido, começar sem briefing, tentar adivinhar o cliente, montar campanha sem lógica aprovada, deixar Criação sem direção, esperar mês acabar para pensar o próximo, tratar social/web/CRM como coisas separadas, focar só em tráfego.",
          "Dupla Performance + Criação: Performance pensa, estrutura, define, analisa, apresenta e corrige direção. Criação solicita material, produz, aprova, programa e executa a parte visual e operacional.",
        ],
      },
    ],
  },
  manual: {
    titulo: "Manual de Comunicação — Performance",
    subtitulo: "Scripts completos para cada momento da operação de Performance",
    blocos: [
      {
        id: "perf-b1",
        titulo: "Bloco 1 — Início da Operação",
        scripts: [
          {
            id: "perf-s1", numero: 1,
            titulo: "Entrada no grupo e boas-vindas",
            situacao: "Cliente acabou de entrar na operação.",
            objetivo: "Gerar segurança, mostrar organização e explicar o próximo passo.",
            oQueClientePrecisaEntender: "Que existe um processo claro, que ele será conduzido e que o início da operação tem uma lógica.",
            scriptCurto: "Olá, [nome]. Seja bem-vindo à Noexcuse. Eu vou conduzir sua operação de performance e nosso próximo passo agora é a reunião de briefing, que vai nos ajudar a montar sua estratégia da forma correta.",
            scriptCompleto: "Olá, [nome]. Tudo bem?\n\nSeja bem-vindo à Noexcuse.\n\nEu sou o responsável pela sua operação de performance e vou conduzir junto com o time toda a parte estratégica da sua estrutura, desde o alinhamento inicial até a execução e o acompanhamento dos resultados.\n\nNosso próximo passo agora é a reunião de briefing. Essa é uma etapa muito importante porque é nela que vamos entender melhor seu negócio, seus objetivos, o que você contratou, como sua estrutura funciona hoje e o que precisamos organizar para montar sua estratégia da forma correta.\n\nAntes da reunião, vou te enviar um checklist com alguns pontos importantes para você já chegar mais preparado.",
            tomIdeal: "Seguro, receptivo, profissional.",
            erroAEvitar: "Falar de forma genérica demais ou parecer que 'vai começar a mexer em campanha' sem antes contextualizar.",
          },
          {
            id: "perf-s2", numero: 2,
            titulo: "Explicação rápida do processo",
            situacao: "Cliente entrou e ainda não entendeu o fluxo da operação.",
            objetivo: "Dar visão geral sem sobrecarregar.",
            oQueClientePrecisaEntender: "Que existe uma sequência: briefing, estratégia, aprovação, execução, acompanhamento.",
            scriptCurto: "Nosso processo funciona assim: primeiro fazemos o briefing, depois montamos sua estratégia, apresentamos tudo para aprovação e, a partir disso, entramos na execução e no acompanhamento mensal.",
            scriptCompleto: "Quero te dar uma visão rápida de como nossa operação funciona.\n\nPrimeiro fazemos a reunião de briefing, onde entendemos melhor seu negócio. Depois, organizamos e montamos sua estratégia completa.\n\nNa sequência, apresentamos esse plano para você. Com a aprovação, seguimos para a execução: campanhas, criativos, site, CRM e acompanhamento.\n\nAlém disso, você terá relatórios diários, otimização semanal e reunião mensal para revisar o que está funcionando e ajustar o próximo ciclo.",
            tomIdeal: "Didático, simples, organizado.",
            erroAEvitar: "Explicar tudo de forma longa demais ou com excesso de jargão.",
          },
          {
            id: "perf-s3", numero: 3,
            titulo: "Envio do checklist pré-briefing",
            situacao: "Hora de preparar o cliente para a primeira reunião.",
            objetivo: "Garantir que a reunião seja produtiva.",
            oQueClientePrecisaEntender: "Que o checklist não é burocracia; ele ajuda a montar uma estratégia melhor.",
            scriptCurto: "Estou te enviando o checklist pré-briefing. Ele vai nos ajudar a fazer uma reunião mais produtiva e montar sua estrutura com mais clareza e mais segurança.",
            scriptCompleto: "Olá, [nome].\n\nEstou te enviando o checklist pré-briefing.\n\nEsse material é importante porque ele ajuda a deixar nossa primeira reunião muito mais produtiva. Com esses pontos organizados antes da conversa, conseguimos entender melhor seu cenário atual e montar uma estratégia mais segura.\n\nNesse checklist você vai ver os acessos e informações que precisamos preparar para a reunião. Se tiver qualquer dúvida sobre algum item, pode me chamar.",
            tomIdeal: "Didático, firme, útil.",
            erroAEvitar: "Passar o checklist sem explicar por que ele existe.",
          },
          {
            id: "perf-s4", numero: 4,
            titulo: "Explicando por que os acessos são necessários",
            situacao: "Cliente pergunta por que precisa liberar acessos.",
            objetivo: "Reduzir resistência e mostrar valor.",
            oQueClientePrecisaEntender: "Que sem acesso a análise fica incompleta.",
            scriptCurto: "Esses acessos são importantes porque eles nos mostram o que já existe hoje e o que precisa ser mantido, corrigido ou refeito na sua estrutura.",
            scriptCompleto: "Esses acessos são importantes porque, sem eles, a gente não consegue enxergar sua estrutura atual com clareza.\n\nPara montar uma estratégia boa, precisamos entender o que já foi feito, o que já existe, o que está certo, o que está errado, o que pode ser aproveitado e o que precisa ser reestruturado.\n\nO acesso não é só uma parte técnica. Ele é base para análise e tomada de decisão.",
            tomIdeal: "Seguro, racional, simples.",
            erroAEvitar: "Soar técnico demais ou dar a impressão de que o acesso é só exigência interna.",
          },
          {
            id: "perf-s5", numero: 5,
            titulo: "Quando o cliente não sabe liberar acesso",
            situacao: "Cliente trava na parte técnica.",
            objetivo: "Acalmar e manter o processo andando.",
            oQueClientePrecisaEntender: "Que ele não precisa dominar isso; haverá orientação.",
            scriptCurto: "Sem problema. Isso acontece bastante. Na própria reunião eu posso te orientar e te ajudar a entender como liberar isso da forma correta.",
            scriptCompleto: "Sem problema. Isso é mais comum do que parece.\n\nNa própria reunião eu posso te orientar nesse processo. O importante é que você já entre com o máximo de informação possível.\n\nSe preferir, também posso te dizer antes exatamente o que você precisa verificar para chegar mais preparado.",
            tomIdeal: "Calmo, tranquilizador, prático.",
            erroAEvitar: "Passar impaciência ou tratar como algo óbvio.",
          },
          {
            id: "perf-s6", numero: 6,
            titulo: "Confirmação da reunião de briefing",
            situacao: "Reunião já marcada.",
            objetivo: "Reforçar importância e reduzir chance de reunião fraca.",
            oQueClientePrecisaEntender: "Que essa reunião é base da estratégia.",
            scriptCurto: "Confirmando nossa reunião de briefing para [dia] às [horário]. Essa reunião vai ser a base da estratégia, então é importante entrar com os pontos do checklist em mãos.",
            scriptCompleto: "Olá, [nome].\n\nConfirmando nossa reunião de briefing para [dia] às [horário].\n\nEssa reunião é importante porque ela vai ser a base da estratégia que vamos construir. Quanto mais completo estiver esse momento, mais clareza teremos.\n\nSe conseguir, entre já com os materiais e acessos do checklist em mãos.",
            tomIdeal: "Objetivo, estratégico, organizado.",
            erroAEvitar: "Confirmar sem reforçar o valor da reunião.",
          },
        ],
      },
      {
        id: "perf-b2",
        titulo: "Bloco 2 — Briefing",
        scripts: [
          {
            id: "perf-s7", numero: 7,
            titulo: "Abertura da reunião de briefing",
            situacao: "Início da reunião.",
            objetivo: "Alinhar expectativa e posicionar o briefing corretamente.",
            oQueClientePrecisaEntender: "Que hoje o foco é entender o negócio e montar base estratégica.",
            scriptCurto: "Hoje o foco aqui é entender sua estrutura, seu negócio e seus objetivos para montarmos a estratégia da forma correta.",
            scriptCompleto: "Antes de começarmos, quero te explicar rapidinho o objetivo dessa reunião.\n\nHoje não é uma reunião para sair falando de anúncio isoladamente. O foco aqui é entender sua estrutura, seu negócio, seu momento, o que você vende, para quem vende, como vende, o que já deu certo, o que travou até aqui e o que você espera dessa operação.\n\nA partir disso, a gente monta a estratégia completa.",
            tomIdeal: "Seguro, didático, claro.",
            erroAEvitar: "Entrar direto nas perguntas sem contextualizar.",
          },
          {
            id: "perf-s8", numero: 8,
            titulo: "Explicação do processo na reunião",
            situacao: "Momento de apresentar canais e rotina operacional.",
            objetivo: "Dar clareza sobre como a operação funciona.",
            oQueClientePrecisaEntender: "Onde fala cada assunto e como será o contato.",
            scriptCurto: "O WhatsApp fica para alinhamentos e marcações. O eKyte será usado para aprovações, tickets e organização do projeto. E você receberá relatórios diários por e-mail.",
            scriptCompleto: "O WhatsApp fica como canal mais rápido para alinhamentos. O eKyte será a plataforma onde ficam aprovações, tickets e organização do projeto. Você vai receber relatórios diários por e-mail.\n\nTambém teremos otimizações semanais e uma reunião mensal estratégica.",
            tomIdeal: "Didático, simples, organizado.",
            erroAEvitar: "Explicar de forma confusa ou misturar demais os canais.",
          },
          {
            id: "perf-s9", numero: 9,
            titulo: "Explicando a importância do briefing",
            situacao: "Cliente parece apressado ou acha que a reunião é formalidade.",
            objetivo: "Mostrar que o briefing é matéria-prima da estratégia.",
            oQueClientePrecisaEntender: "Que quanto melhor ele falar, melhor fica a estrutura.",
            scriptCurto: "Essa reunião é importante porque daqui sai a base da sua estratégia. Quanto melhor entendermos seu negócio, mais assertiva tende a ser a estrutura depois.",
            scriptCompleto: "Essa reunião é muito importante porque é daqui que sai a base da sua estratégia.\n\nQuanto melhor a gente entender seu negócio, sua oferta, seu público, seu comercial e sua realidade, mais assertiva tende a ser a estrutura que vamos montar.\n\nHoje eu vou te fazer perguntas mais estratégicas, e o objetivo é justamente te ouvir bastante.",
            tomIdeal: "Didático, estratégico, próximo.",
            erroAEvitar: "Tratar o briefing como coleta burocrática de informação.",
          },
          {
            id: "perf-s10", numero: 10,
            titulo: "Transição para o cliente falar mais",
            situacao: "Início da parte investigativa.",
            objetivo: "Tirar o peso do 'responder certo' e liberar a fala do cliente.",
            oQueClientePrecisaEntender: "Que ele precisa trazer a visão real, não uma versão 'bonita'.",
            scriptCurto: "Aqui o mais importante não é responder de forma perfeita. É me mostrar sua visão real do negócio e do que acontece no dia a dia.",
            scriptCompleto: "Agora eu vou entrar em algumas perguntas mais importantes.\n\nAqui o mais importante não é me responder de forma perfeita. É me mostrar sua visão real do negócio, do que acontece no dia a dia, do que funciona, do que trava e do que você quer alcançar.\n\nQuanto mais verdade a gente tiver aqui, melhor fica a estratégia depois.",
            tomIdeal: "Acolhedor, inteligente, leve.",
            erroAEvitar: "Pressionar o cliente a responder de forma técnica.",
          },
          {
            id: "perf-s11", numero: 11,
            titulo: "Perguntas sobre negócio e oferta",
            situacao: "Entendimento da operação.",
            objetivo: "Extrair base para posicionamento e campanhas.",
            oQueClientePrecisaEntender: "Que vocês precisam compreender o negócio, não só anunciar.",
            scriptCurto: "Quero entender melhor o que você vende hoje com mais força, o que é prioridade e o que faz alguém escolher sua empresa.",
            scriptCompleto: "Quero começar entendendo melhor sua operação hoje.\n\nMe explica:\n• o que você vende hoje com mais força\n• quais produtos ou serviços são mais importantes\n• qual entrega é prioridade\n• qual é a principal dor que seu cliente chega tendo\n• o que faz alguém escolher sua empresa e não outra",
            tomIdeal: "Curioso, claro, consultivo.",
            erroAEvitar: "Fazer perguntas frias, sem contexto.",
          },
          {
            id: "perf-s12", numero: 12,
            titulo: "Perguntas sobre público",
            situacao: "Mapeamento de audiência.",
            objetivo: "Entender dor, desejo e decisão.",
            oQueClientePrecisaEntender: "Que público não é só demografia; é comportamento e necessidade.",
            scriptCurto: "Quero entender melhor quem é o cliente que você quer atrair, o que ele busca e o que costuma travar a decisão dele.",
            scriptCompleto: "Agora quero entender melhor quem é o cliente que você quer atrair.\n\nMe explica:\n• quem é esse público\n• o que ele busca\n• qual problema ele quer resolver\n• o que ele costuma valorizar\n• o que costuma travar a decisão dele",
            tomIdeal: "Investigativo, simples, atento.",
            erroAEvitar: "Limitar a pergunta a idade/cidade apenas.",
          },
          {
            id: "perf-s13", numero: 13,
            titulo: "Perguntas sobre metas e expectativa",
            situacao: "Alinhamento de objetivo.",
            objetivo: "Tirar a conversa do genérico.",
            oQueClientePrecisaEntender: "Que meta orienta estrutura, investimento e leitura.",
            scriptCurto: "Quero entender qual é o principal resultado que você quer gerar e o que faria você sentir que estamos no caminho certo.",
            scriptCompleto: "Agora quero entender com clareza o que você espera dessa operação.\n\nQual é o principal resultado que você quer gerar? Mais leads? Mais vendas? Mais oportunidades?\n\nE além disso:\n• qual meta faria sentido\n• em quanto tempo espera começar a sentir evolução\n• o que para você seria sinal de que estamos no caminho certo",
            tomIdeal: "Objetivo, comercial, claro.",
            erroAEvitar: "Assumir meta sem perguntar.",
          },
          {
            id: "perf-s14", numero: 14,
            titulo: "Perguntas sobre histórico",
            situacao: "Levantamento do que já foi tentado.",
            objetivo: "Evitar repetir erro e aproveitar aprendizados.",
            oQueClientePrecisaEntender: "Que vocês querem entender o passado para montar melhor o futuro.",
            scriptCurto: "Quero entender o que já foi feito até aqui e o que você sentiu que funcionou ou travou.",
            scriptCompleto: "Quero entender também o que já foi tentado até aqui.\n\nMe conta:\n• o que já fez de marketing ou tráfego pago\n• o que pareceu funcionar\n• o que sentiu que não funcionou\n• se já teve campanha rodando\n• se já teve site ou landing page\n• se já existe algum processo comercial ou CRM\n\nIsso ajuda porque a gente não parte do zero no escuro.",
            tomIdeal: "Consultivo, simples, respeitoso.",
            erroAEvitar: "Soar julgador sobre o que já foi feito.",
          },
          {
            id: "perf-s15", numero: 15,
            titulo: "Perguntas sobre comercial e CRM",
            situacao: "Mapear aproveitamento das oportunidades.",
            objetivo: "Entender se a operação comercial sustenta o marketing.",
            oQueClientePrecisaEntender: "Que não adianta gerar lead e perder na sequência.",
            scriptCurto: "Quero entender como funciona seu atendimento e seu processo comercial hoje, porque isso interfere diretamente no aproveitamento das oportunidades.",
            scriptCompleto: "Essa parte é muito importante porque campanha boa sem processo comercial bom perde força.\n\nQuero entender:\n• como chegam os contatos hoje\n• quem atende\n• quanto tempo demora para responder\n• como funciona o fechamento\n• se existe follow-up",
            tomIdeal: "Consultivo, estratégico, claro.",
            erroAEvitar: "Pular essa etapa ou não ir fundo o suficiente.",
          },
          {
            id: "perf-s16", numero: 16,
            titulo: "Fechamento da reunião de briefing",
            situacao: "Fim da reunião.",
            objetivo: "Concluir com segurança e mostrar próximos passos.",
            oQueClientePrecisaEntender: "Que agora entra a fase de construção estratégica.",
            scriptCurto: "Com tudo o que você trouxe hoje, já temos uma base muito melhor para montar sua estratégia. Nosso próximo passo é organizar isso e te apresentar a estrutura completa.",
            scriptCompleto: "Perfeito. Com tudo o que você trouxe hoje, já temos uma base bem mais clara para montar sua estrutura.\n\nNosso próximo passo é organizar essas informações, analisar o cenário e construir a estratégia completa.\n\nDepois, marcamos a reunião de apresentação, onde eu vou te mostrar o que será feito, por quê e como.",
            tomIdeal: "Seguro, claro, conclusivo.",
            erroAEvitar: "Encerrar sem explicar o que acontece depois.",
          },
        ],
      },
      {
        id: "perf-b3",
        titulo: "Bloco 3 — Apresentação da Estratégia",
        scripts: [
          {
            id: "perf-s17", numero: 17,
            titulo: "Marcação da reunião de apresentação",
            situacao: "Estratégia pronta.",
            objetivo: "Agendar a reunião de validação.",
            oQueClientePrecisaEntender: "Que essa é a reunião onde tudo ganha forma.",
            scriptCurto: "Finalizamos sua estratégia e quero marcar a reunião de apresentação para te mostrar toda a estrutura que montamos.",
            scriptCompleto: "Olá, [nome].\n\nFinalizamos a estrutura da sua estratégia e quero marcar com você a reunião de apresentação.\n\nNessa reunião eu vou te mostrar, de forma organizada, tudo o que foi pensado:\n• o que será feito\n• por que será feito\n• como isso se conecta\n• e como essa estrutura vai funcionar no mês\n\nQual desses horários funciona melhor para você: [opção 1] ou [opção 2]?",
            tomIdeal: "Objetivo, confiante, organizado.",
            erroAEvitar: "Marcar a reunião sem vender a importância dela.",
          },
          {
            id: "perf-s18", numero: 18,
            titulo: "Abertura da apresentação da estratégia",
            situacao: "Início da reunião.",
            objetivo: "Enquadrar a apresentação de forma estratégica.",
            oQueClientePrecisaEntender: "Que vai ver lógica, não só entregas.",
            scriptCurto: "Hoje eu vou te apresentar a estrutura que montamos com base no briefing, no que você contratou e no melhor caminho estratégico.",
            scriptCompleto: "Hoje eu vou te apresentar a estrutura que montamos com base no briefing e no que entendemos como caminho mais estratégico para sua operação.\n\nA ideia aqui não é só te mostrar entregas. É te mostrar a lógica da estrutura: o papel dos conteúdos, dos criativos, das campanhas, do site e do CRM dentro do objetivo que você quer alcançar.",
            tomIdeal: "Seguro, comercial, didático.",
            erroAEvitar: "Começar listando tarefas sem contexto.",
          },
          {
            id: "perf-s19", numero: 19,
            titulo: "Explicando a lógica da estratégia",
            situacao: "Cliente precisa entender a estrutura como sistema.",
            objetivo: "Mostrar conexão entre as partes.",
            oQueClientePrecisaEntender: "Que nada está solto.",
            scriptCurto: "Tudo o que você vai ver aqui foi pensado para funcionar de forma conectada. Nada entra solto.",
            scriptCompleto: "Tudo o que você vai ver aqui foi pensado para funcionar de forma conectada.\n\nOu seja:\n• os conteúdos têm um papel\n• os criativos têm um papel\n• as campanhas têm um papel\n• o site tem um papel\n• o CRM tem um papel\n\nNada entra de forma solta. A ideia é fazer com que a estrutura inteira trabalhe na mesma direção.",
            tomIdeal: "Estratégico, simples, forte.",
            erroAEvitar: "Explicar cada peça isoladamente.",
          },
          {
            id: "perf-s20", numero: 20,
            titulo: "Explicando as copys",
            situacao: "Apresentação da linha de mensagem.",
            objetivo: "Dar valor às copys como base da operação.",
            oQueClientePrecisaEntender: "Que as copys dão direção à comunicação.",
            scriptCurto: "As copys não são textos soltos. Elas dão base para o conteúdo, criativos, anúncios e comunicação da operação.",
            scriptCompleto: "As copys que montamos aqui não são textos isolados. Elas servem para sustentar a comunicação da operação.\n\nElas ajudam a dar direção para:\n• o conteúdo\n• os criativos\n• os anúncios\n• as páginas\n• e até a abordagem comercial\n\nOu seja, elas entram como base da mensagem que vai ser levada para o público.",
            tomIdeal: "Didático, claro, estratégico.",
            erroAEvitar: "Tratar copy como legenda ou texto avulso apenas.",
          },
          {
            id: "perf-s21", numero: 21,
            titulo: "Explicando a estratégia de tráfego",
            situacao: "Apresentação das campanhas.",
            objetivo: "Mostrar que investimento terá direção.",
            oQueClientePrecisaEntender: "Que não é 'subir anúncio', é estruturar investimento.",
            scriptCurto: "A estrutura de tráfego foi pensada para dar direção ao investimento, com campanha, público, objetivo e criativo organizados.",
            scriptCompleto: "A estrutura de tráfego foi pensada para não sair simplesmente subindo anúncio.\n\nO que definimos aqui foi:\n• quais campanhas entram\n• em quais plataformas\n• com qual objetivo\n• para qual público\n• com qual lógica de investimento\n\nIsso é importante porque o investimento precisa de direção.",
            tomIdeal: "Seguro, racional, comercial.",
            erroAEvitar: "Falar só de plataforma e orçamento.",
          },
          {
            id: "perf-s22", numero: 22,
            titulo: "Explicando o site ou landing page",
            situacao: "Apresentação da parte web.",
            objetivo: "Mostrar função comercial da página.",
            oQueClientePrecisaEntender: "Que o site ajuda a converter.",
            scriptCurto: "A página não foi pensada só para existir. Ela foi organizada para ajudar a apresentar a oferta, gerar confiança e conduzir a ação.",
            scriptCompleto: "A página não foi pensada só para ter um site.\n\nEla foi organizada para cumprir uma função dentro da estrutura:\n• apresentar a oferta\n• gerar clareza\n• passar confiança\n• conduzir a ação\n• ajudar na conversão\n\nCada bloco, cada seção e cada CTA têm um motivo de existir.",
            tomIdeal: "Didático, comercial, claro.",
            erroAEvitar: "Falar do site como vitrine institucional apenas.",
          },
          {
            id: "perf-s23", numero: 23,
            titulo: "Explicando o CRM",
            situacao: "Apresentação da parte de CRM.",
            objetivo: "Mostrar que CRM protege as oportunidades geradas.",
            oQueClientePrecisaEntender: "Que lead sem acompanhamento se perde.",
            scriptCurto: "O CRM entra para organizar o que acontece depois que o lead chega e evitar perda de oportunidade.",
            scriptCompleto: "O CRM entra para organizar o que acontece depois que o lead chega.\n\nPorque não adianta investir para gerar oportunidade se depois o contato entra e se perde.\n\nEntão essa parte da estrutura serve para:\n• organizar leads\n• acompanhar negociações\n• evitar perda de oportunidade",
            tomIdeal: "Didático, comercial, claro.",
            erroAEvitar: "Falar do CRM só pelo lado técnico.",
          },
          {
            id: "perf-s24", numero: 24,
            titulo: "Pedido de aprovação da estratégia",
            situacao: "Fim da apresentação.",
            objetivo: "Conduzir aprovação com segurança.",
            oQueClientePrecisaEntender: "Que a aprovação libera a execução.",
            scriptCurto: "Com a sua aprovação, seguimos para a fase de execução da estrutura.",
            scriptCompleto: "Essa é a estrutura que montamos para o seu ciclo.\n\nA partir da sua aprovação, seguimos com:\n• criação dos materiais\n• implantação das campanhas\n• estruturação do site, se houver\n• organização do CRM, se houver\n\nQuero ouvir agora seus pontos, dúvidas e percepções.",
            tomIdeal: "Confiante, aberto, objetivo.",
            erroAEvitar: "Pedir aprovação de forma apressada.",
          },
        ],
      },
      {
        id: "perf-b4",
        titulo: "Bloco 4 — Execução e Acompanhamento",
        scripts: [
          {
            id: "perf-s25", numero: 25,
            titulo: "Aprovação recebida",
            situacao: "Cliente aprovou a estratégia.",
            objetivo: "Mostrar avanço e próximos passos.",
            oQueClientePrecisaEntender: "Que agora a estratégia sai do plano e entra em execução.",
            scriptCurto: "Perfeito. Com essa aprovação, seguimos agora para a fase de execução da estrutura.",
            scriptCompleto: "Perfeito, [nome].\n\nCom essa aprovação, seguimos agora para a fase de execução:\n• criação dos materiais\n• implantação das campanhas\n• andamento do site\n• CRM, quando aplicável\n\nA partir daqui, o trabalho começa a sair do plano e entrar em execução.",
            tomIdeal: "Objetivo, positivo, seguro.",
            erroAEvitar: "Responder apenas 'ok' ou 'recebido'.",
          },
          {
            id: "perf-s26", numero: 26,
            titulo: "Quando há ajuste pontual na estratégia",
            situacao: "Cliente pediu alteração pequena.",
            objetivo: "Acolher sem perder estrutura.",
            oQueClientePrecisaEntender: "Que o ajuste será feito preservando a lógica do plano.",
            scriptCurto: "Faz sentido. Vou ajustar essa parte e reorganizar o que for necessário para manter a estratégia coerente.",
            scriptCompleto: "Perfeito. Faz sentido me trazer esse ponto.\n\nVou ajustar essa parte da estrutura e reorganizar o que for necessário para que a estratégia continue coerente como um todo. Assim que estiver alinhado, seguimos com a execução.",
            tomIdeal: "Aberto, técnico na medida, seguro.",
            erroAEvitar: "Parecer defensivo ou rígido demais.",
          },
          {
            id: "perf-s27", numero: 27,
            titulo: "Quando o cliente quer mudar muita coisa",
            situacao: "Mudanças grandes após apresentação.",
            objetivo: "Separar ajuste de mudança estrutural.",
            oQueClientePrecisaEntender: "Que parte disso já mexe no plano, não só no detalhe.",
            scriptCurto: "Alguns pontos entram como ajuste, mas outros já mexem mais na direção da estratégia. Vou reorganizar isso com cuidado.",
            scriptCompleto: "Entendi seus pontos.\n\nAlguns deles entram como ajuste normal, mas outros já mexem mais na direção da estratégia que foi aprovada. Então vou reorganizar isso com cuidado para separar o que é refinamento do que já representa mudança mais estrutural.\n\nAssim seguimos com clareza.",
            tomIdeal: "Calmo, firme, inteligente.",
            erroAEvitar: "Aceitar tudo como se fosse alteração simples.",
          },
          {
            id: "perf-s28", numero: 28,
            titulo: "Explicando o investimento em tráfego",
            situacao: "Cliente quer entender o valor aplicado.",
            objetivo: "Mostrar relação entre investimento e estrutura.",
            oQueClientePrecisaEntender: "Que investimento precisa conversar com meta e capacidade.",
            scriptCurto: "O investimento em tráfego precisa ter direção. Ele conversa com meta, campanha, público, estrutura comercial e com o que queremos gerar.",
            scriptCompleto: "O investimento em tráfego não é só um valor colocado para rodar anúncio.\n\nEle precisa ser entendido como parte da estrutura de geração de oportunidade. O que fazemos é organizar esse investimento para que ele tenha objetivo, direção, leitura e ajuste.\n\nO valor investido precisa conversar com:\n• a meta\n• o momento da operação\n• a capacidade comercial\n• o tipo de campanha",
            tomIdeal: "Racional, claro, consultivo.",
            erroAEvitar: "Dar resposta simplista ou mágica.",
          },
          {
            id: "perf-s29", numero: 29,
            titulo: "Quando o cliente pergunta 'quanto preciso investir?'",
            situacao: "Definição de verba.",
            objetivo: "Responder sem simplificar demais.",
            oQueClientePrecisaEntender: "Que não existe número mágico.",
            scriptCurto: "O investimento ideal depende do seu objetivo, da velocidade que você espera e da estrutura que estamos colocando para rodar.",
            scriptCompleto: "O investimento ideal depende do que você quer alcançar, da velocidade que espera e da estrutura que estamos montando.\n\nNão existe um número mágico. O que existe é uma construção coerente entre objetivo, canal, campanha, público, capacidade de atendimento e tempo de aprendizado.\n\nNosso papel é montar essa direção de forma realista e estratégica.",
            tomIdeal: "Didático, seguro, honesto.",
            erroAEvitar: "Dar resposta vaga demais ou arbitrária.",
          },
          {
            id: "perf-s30", numero: 30,
            titulo: "Quando o cliente quer resultado imediato",
            situacao: "Expectativa de velocidade alta.",
            objetivo: "Ajustar expectativa sem esfriar a operação.",
            oQueClientePrecisaEntender: "Que resultado rápido é desejado, mas estrutura importa.",
            scriptCurto: "Nosso foco é gerar resultado o mais rápido possível, mas com estrutura, para que a operação não dependa só de um pico isolado.",
            scriptCompleto: "Entendo totalmente sua expectativa.\n\nO nosso foco é gerar resultado o mais rápido possível, mas também com estrutura. Porque quando a operação nasce organizada, a chance de ganhar consistência aumenta muito.\n\nAlgumas respostas podem vir rápido. Mas o trabalho mais saudável é construir uma operação que não dependa de sorte.",
            tomIdeal: "Empático, realista, firme.",
            erroAEvitar: "Prometer demais ou esfriar demais.",
          },
        ],
      },
      {
        id: "perf-b5",
        titulo: "Bloco 5 — Otimização Semanal",
        scripts: [
          {
            id: "perf-s31", numero: 31,
            titulo: "Envio da otimização semanal",
            situacao: "Contato semanal recorrente.",
            objetivo: "Manter cliente atualizado e mostrar ação.",
            oQueClientePrecisaEntender: "Que a operação está sendo acompanhada de verdade.",
            scriptCurto: "Segue a atualização desta semana da sua operação, com o que foi analisado, ajustado e o que está respondendo melhor ou pedindo atenção.",
            scriptCompleto: "Olá, [nome].\n\nSegue a atualização desta semana da sua operação.\n\nNela estou te mostrando, de forma objetiva:\n• o que foi analisado\n• o que foi ajustado\n• o que está respondendo melhor\n• o que pede atenção",
            tomIdeal: "Claro, didático, ativo.",
            erroAEvitar: "Mandar números sem contexto.",
          },
          {
            id: "perf-s32", numero: 32,
            titulo: "Pedido de feedback dentro da otimização",
            situacao: "Abrir espaço para visão do cliente.",
            objetivo: "Trazer inteligência comercial e de mercado.",
            oQueClientePrecisaEntender: "Que o feedback dele ajuda a ajustar melhor.",
            scriptCurto: "Se teve alguma percepção nova da equipe, do comercial ou do mercado nesta semana, isso pode ajudar bastante a refinar a operação.",
            scriptCompleto: "Além dos ajustes que fizemos por aqui, quero aproveitar para abrir espaço para seu feedback também.\n\nSe teve alguma percepção nova da equipe, do comercial ou do mercado nesta semana, isso pode ajudar a refinar a estrutura e a leitura da operação.",
            tomIdeal: "Aberto, colaborativo, estratégico.",
            erroAEvitar: "Transformar a atualização em monólogo.",
          },
          {
            id: "perf-s33", numero: 33,
            titulo: "Quando a performance identifica problema na criação",
            situacao: "Criativo, mensagem ou material enfraquecendo a operação.",
            objetivo: "Informar sem gerar insegurança.",
            oQueClientePrecisaEntender: "Que o problema foi identificado e está sendo tratado.",
            scriptCurto: "Identificamos um ponto na parte dos materiais que pode estar impactando a força da operação, e já estamos tratando isso internamente.",
            scriptCompleto: "Olá, [nome].\n\nEm nossa leitura desta semana, identificamos um ponto importante na parte dos materiais que pode estar impactando a força da operação.\n\nJá estamos tratando isso internamente para ajustar e melhorar a próxima etapa.",
            tomIdeal: "Seguro, técnico na medida, transparente.",
            erroAEvitar: "Jogar a culpa na criação ou no cliente.",
          },
          {
            id: "perf-s34", numero: 34,
            titulo: "Quando a performance identifica problema no comercial",
            situacao: "Lead chega, mas processo comercial enfraquece resultado.",
            objetivo: "Trazer o tema com diplomacia.",
            oQueClientePrecisaEntender: "Que campanha e comercial precisam trabalhar juntos.",
            scriptCurto: "Percebemos um ponto no processo comercial que pode estar interferindo no aproveitamento das oportunidades geradas.",
            scriptCompleto: "Olá, [nome].\n\nEm nossa leitura da operação, percebemos um ponto importante no processo comercial que pode estar interferindo no aproveitamento das oportunidades.\n\nNão necessariamente isso invalida a campanha, mas mostra que existe um ajuste importante depois da entrada do lead.",
            tomIdeal: "Diplomático, objetivo, colaborativo.",
            erroAEvitar: "Soar acusatório.",
          },
        ],
      },
      {
        id: "perf-b6",
        titulo: "Bloco 6 — Reunião Mensal",
        scripts: [
          {
            id: "perf-s35", numero: 35,
            titulo: "Marcação da reunião mensal",
            situacao: "Hora de preparar o próximo ciclo.",
            objetivo: "Garantir antecedência e alinhamento.",
            oQueClientePrecisaEntender: "Que a reunião mensal revisa o ciclo e abre o próximo.",
            scriptCurto: "Quero alinhar com você a reunião mensal para revisarmos este ciclo e prepararmos o próximo com antecedência.",
            scriptCompleto: "Olá, [nome].\n\nQuero alinhar com você a reunião mensal da sua operação.\n\nNessa reunião vamos:\n• revisar o ciclo atual\n• olhar os aprendizados\n• ouvir seu feedback\n• entender o que funcionou e o que precisa mudar\n• e apresentar a estrutura do próximo ciclo\n\nTenho estes horários disponíveis: [opção 1] e [opção 2]. Qual funciona melhor?",
            tomIdeal: "Objetivo, estratégico, claro.",
            erroAEvitar: "Marcar sem reforçar o valor da reunião.",
          },
          {
            id: "perf-s36", numero: 36,
            titulo: "Abertura da reunião mensal",
            situacao: "Início da reunião.",
            objetivo: "Mostrar que a leitura vai além de números.",
            oQueClientePrecisaEntender: "Que o foco é aprender e melhorar a estrutura.",
            scriptCurto: "Hoje vamos olhar o que aconteceu neste ciclo e entender o que esses dados estão mostrando sobre a sua estrutura.",
            scriptCompleto: "Hoje vamos olhar o que aconteceu neste ciclo e, mais importante do que só ver número, entender o que esses dados estão mostrando sobre sua estrutura.\n\nA ideia é enxergar:\n• o que respondeu melhor\n• o que precisa de ajuste\n• o que vamos manter\n• o que vamos mudar",
            tomIdeal: "Analítico, calmo, confiante.",
            erroAEvitar: "Começar direto por métrica sem contexto.",
          },
          {
            id: "perf-s37", numero: 37,
            titulo: "Quando o resultado ainda não veio como esperado",
            situacao: "Ciclo com resposta abaixo do esperado.",
            objetivo: "Ser honesto e ao mesmo tempo construtivo.",
            oQueClientePrecisaEntender: "Que o cenário não será maquiado, mas que há direção.",
            scriptCurto: "Neste momento, a operação ainda não entregou o nível de resposta que buscamos, mas os dados já mostram onde estão os gargalos.",
            scriptCompleto: "Quero ser bem claro com você: neste momento, a operação ainda não entregou o nível de resposta que buscamos.\n\nMas isso não significa que estamos sem direção. O que os dados mostram agora é onde estão os gargalos e quais ajustes precisam entrar para o próximo ciclo.\n\nNosso papel aqui não é maquiar cenário. É identificar com clareza o que precisa ser corrigido.",
            tomIdeal: "Honesto, firme, estratégico.",
            erroAEvitar: "Defensividade ou promessa vazia.",
          },
          {
            id: "perf-s38", numero: 38,
            titulo: "Quando o resultado veio bem",
            situacao: "Ciclo positivo.",
            objetivo: "Transformar acerto em aprendizado.",
            oQueClientePrecisaEntender: "Que o foco é consolidar, não comemorar e relaxar.",
            scriptCurto: "Temos sinais bons neste ciclo. Agora o foco é entender o que puxou esse desempenho para fortalecer o próximo passo.",
            scriptCompleto: "Temos sinais bons neste ciclo.\n\nO mais importante agora é entender o que puxou esse desempenho, para que a gente não trate isso só como acerto pontual, mas como aprendizado para fortalecer o próximo ciclo.\n\nNosso foco agora é manter o que está funcionando e refinar o que ainda pode evoluir.",
            tomIdeal: "Seguro, positivo, analítico.",
            erroAEvitar: "Empolgação vazia ou leitura superficial.",
          },
        ],
      },
      {
        id: "perf-b7",
        titulo: "Bloco 7 — Objeções e Dúvidas",
        scripts: [
          {
            id: "perf-s40", numero: 40,
            titulo: "\"Já tentei tráfego e não deu certo\"",
            situacao: "Cliente traz frustração passada.",
            objetivo: "Reposicionar a conversa em estrutura, não em promessa.",
            oQueClientePrecisaEntender: "Que o problema anterior pode ter sido estrutural.",
            scriptCurto: "Isso é mais comum do que parece. Muitas vezes o problema não está só no tráfego, mas na estrutura como um todo.",
            scriptCompleto: "Isso é mais comum do que parece. Nem sempre o problema está só no tráfego em si. Muitas vezes o que falha é a estrutura como um todo:\n\n• campanha mal organizada\n• criativo fraco\n• oferta mal apresentada\n• página ruim\n• comercial lento\n• falta de acompanhamento\n\nO que fazemos aqui é montar essa estrutura de forma mais completa.",
            tomIdeal: "Empático, estratégico, seguro.",
            erroAEvitar: "Criticar demais o trabalho anterior ou prometer que 'agora vai'.",
          },
          {
            id: "perf-s41", numero: 41,
            titulo: "\"Quero subir campanha logo\"",
            situacao: "Cliente quer acelerar pulando estrutura.",
            objetivo: "Segurar com lógica, sem parecer travado.",
            oQueClientePrecisaEntender: "Que rapidez sem base pode desperdiçar investimento.",
            scriptCurto: "Dá para colocar campanha no ar rápido. O ponto é que rapidez sem estrutura costuma gerar desperdício.",
            scriptCompleto: "Dá para colocar campanha no ar rápido. O ponto é que rapidez sem estrutura costuma gerar desperdício.\n\nNosso foco é subir com mais segurança, com lógica de público, criativo, oferta, página e acompanhamento. Isso protege melhor o investimento.",
            tomIdeal: "Firme, racional, estratégico.",
            erroAEvitar: "Soar lento demais ou burocrático demais.",
          },
          {
            id: "perf-s42", numero: 42,
            titulo: "\"Não quero reunião, resolve por mensagem\"",
            situacao: "Resistência a reuniões.",
            objetivo: "Manter reunião quando ela for necessária.",
            oQueClientePrecisaEntender: "Que algumas etapas pedem conversa para evitar erro.",
            scriptCurto: "Podemos adiantar muita coisa por mensagem, mas algumas etapas funcionam melhor em conversa porque exigem contexto e decisão mais completa.",
            scriptCompleto: "Entendo, e a gente pode adiantar muita coisa por mensagem.\n\nMas algumas etapas, principalmente briefing, apresentação estratégica e reunião mensal, funcionam melhor em conversa porque exigem contexto e tomada de decisão mais completa.\n\nA reunião aqui não é burocracia. Ela encurta erro e melhora a clareza do processo.",
            tomIdeal: "Firme, didático, calmo.",
            erroAEvitar: "Ceder ou impor sem explicar.",
          },
          {
            id: "perf-s43", numero: 43,
            titulo: "\"A estratégia está grande demais\"",
            situacao: "Cliente acha a estrutura robusta.",
            objetivo: "Mostrar que clareza evita operação solta.",
            oQueClientePrecisaEntender: "Que a estratégia organiza, não complica.",
            scriptCurto: "A estratégia parece maior porque ela organiza tudo o que sustenta sua operação. O objetivo não é complicar, e sim evitar que seu investimento rode sem direção.",
            scriptCompleto: "Entendo.\n\nA estratégia parece mais robusta porque ela organiza tudo o que sustenta sua operação. O objetivo não é complicar. É evitar que as coisas fiquem soltas e que o investimento rode sem direção.\n\nQuando a estrutura está clara, fica muito mais fácil entender o que está sendo feito, por que e onde mexer para melhorar.",
            tomIdeal: "Didático, comercial, claro.",
            erroAEvitar: "Responder como se o cliente 'não tivesse entendido'.",
          },
          {
            id: "perf-s50", numero: 50,
            titulo: "\"O que vocês estão fazendo de fato?\"",
            situacao: "Cliente quer tangibilizar a operação.",
            objetivo: "Mostrar amplitude do trabalho.",
            oQueClientePrecisaEntender: "Que a operação é contínua, não só campanha.",
            scriptCurto: "Nosso trabalho não fica só em rodar campanha. Estamos estruturando, acompanhando, ajustando e conectando tudo o que sustenta sua operação.",
            scriptCompleto: "Nosso trabalho aqui não fica só em rodar campanha.\n\nO que estamos fazendo é:\n• entendendo sua estrutura\n• montando a estratégia\n• organizando mensagem e direção\n• estruturando campanhas\n• conectando isso com criativos, site e CRM\n• acompanhando dados\n• ajustando o que precisa\n• e preparando o próximo ciclo com antecedência\n\nÉ uma operação contínua, não uma ação isolada.",
            tomIdeal: "Claro, forte, estratégico.",
            erroAEvitar: "Responder só com lista técnica ou defensiva.",
          },
        ],
      },
    ],
  },
};

// ═══════════════════════════════════════════════
// CRIAÇÃO
// ═══════════════════════════════════════════════

export const criacaoData: PlaybookData = {
  playbook: {
    titulo: "Playbook Operacional — Criação",
    subtitulo: "Função de Criação: Social Media, Criativos de Tráfego Pago, Site e Gestão de Demandas",
    sections: [
      {
        id: "cria-obj",
        titulo: "1. Objetivo da função",
        conteudo: [
          "A função de Criação é responsável por executar visualmente e operacionalmente a estratégia já aprovada pelo cliente.",
          "Ela recebe a direção definida pela área de Performance e transforma isso em: artes, vídeos curtos, criativos de tráfego pago, programação de conteúdos sociais, estruturação e finalização de site, gestão de aprovações de materiais, triagem inicial de tickets de criação.",
          "A Criação não é a área que define a estratégia principal. Ela é a área que executa com precisão a estratégia aprovada, garantindo organização, prazo, qualidade e fluxo correto.",
        ],
      },
      {
        id: "cria-entrega",
        titulo: "2. O que a cadeira de Criação entrega",
        conteudo: [
          "A. Conteúdo para Social Media — post estático, carrossel, vídeo curto, adaptação por formato, programação do que for aprovado.",
          "B. Criativos para Tráfego Pago — imagem para campanha, vídeo curto para anúncio, variações de criativo, entregas destinadas ao profissional de Performance.",
          "C. Site — estruturação do escopo visual e funcional, construção na Lovable, solicitação dos materiais finais, finalização visual, preparação para aprovação.",
          "D. Fluxo operacional via eKyte — aprovação dos materiais, programação do que foi aprovado, recebimento de tickets extras, triagem inicial.",
        ],
      },
      {
        id: "cria-ferramentas",
        titulo: "3. Ferramentas da função",
        conteudo: [
          "WhatsApp: envio do checklist, solicitação de materiais, cobrança de prazo, alinhamentos rápidos.",
          "PDF de checklist: formato padrão para solicitar materiais mensalmente.",
          "Google Drive: criar pasta do cliente, organizar upload dos materiais.",
          "eKyte: aprovação dos materiais, programação, envio de tarefas, recebimento de tickets, registro operacional.",
          "Lovable: estruturar e desenvolver o site, montar escopo visual e funcional, finalizar antes da publicação.",
        ],
      },
      {
        id: "cria-posicao",
        titulo: "4. Posição da Criação na operação",
        conteudo: [
          "Quem pensa e apresenta a estratégia: Performance.",
          "A Criação entra depois que o cliente aprova a estratégia.",
          "A partir daí, ela é responsável por: identificar materiais necessários, solicitar ao cliente, receber e validar, produzir artes e vídeos, subir para aprovação, programar social, encaminhar criativos para Performance, desenvolver e finalizar site, receber e triar tickets extras.",
        ],
      },
      {
        id: "cria-gargalo",
        titulo: "5. Principal gargalo da função",
        conteudo: [
          "Solicitar corretamente os materiais e conseguir que o cliente envie no formato e prazo adequados.",
          "Prioridade operacional: 1) entender a estratégia aprovada → 2) transformar em checklist objetivo → 3) solicitar corretamente → 4) cobrar dentro do prazo → 5) só depois produzir.",
        ],
      },
      {
        id: "cria-principios",
        titulo: "6. Princípios obrigatórios",
        conteudo: [
          "1. Nunca pedir material de forma vaga — sempre especificar o que precisa, quantidade, formato, objetivo, prazo.",
          "2. Toda solicitação deve ser padronizada — PDF padrão enviado por WhatsApp.",
          "3. Toda solicitação deve ter prazo — sem data, o cliente atrasa.",
          "4. O cliente deve ter um local claro para envio — pasta no Google Drive.",
          "5. Todo primeiro ciclo precisa de educação do cliente — tutorial de como enviar e gravar.",
          "6. Aprovação não acontece no WhatsApp — aprovação acontece no eKyte.",
          "7. Ticket extra precisa de triagem — verificar contrato antes de executar.",
        ],
      },
      {
        id: "cria-fluxo-social",
        titulo: "7. Fluxo geral — Social e Tráfego",
        conteudo: [
          "Etapa 1 — Receber a estratégia aprovada: copies, linha de conteúdos, direcionamento de criativos, formatos.",
          "Etapa 2 — Quebrar em checklist de materiais: fotos, vídeos, gravações, material institucional.",
          "Etapa 3 — Montar checklist em PDF: nome do cliente, ciclo, lista dos materiais, orientações, prazo, link do Drive.",
          "Etapas 4-7 — Enviar via WhatsApp → Follow-up → Receber e validar materiais → Produzir.",
          "Etapa 8 — Revisão interna: ortografia, copy aplicada, identidade visual, CTA, formato, qualidade.",
          "Etapa 9 — Aprovação no eKyte: subir materiais, organizar social e tráfego, acompanhar retorno.",
          "Etapa 10 — Pós-aprovação: programar social, liberar criativos para Performance, aplicar ajustes.",
        ],
      },
      {
        id: "cria-fluxo-site",
        titulo: "8. Fluxo de Site",
        conteudo: [
          "Etapa 1 — Receber estrutura aprovada: copy, seções, lógica, objetivo.",
          "Etapa 2 — Montar escopo na Lovable: estrutura, blocos, hierarquia visual, CTAs.",
          "Etapa 3 — Mapear materiais faltantes: fotos reais, vídeos, imagens institucionais.",
          "Etapa 4 — Solicitar materiais: checklist PDF, WhatsApp, link Drive, prazo.",
          "Etapa 5 — Produção e finalização: inserir no site, ajustar visual, revisar desktop/mobile.",
          "Etapa 6 — Aprovação via ambiente temporário de preview (preview.seudominio.com.br).",
          "Etapa 7 — Publicação final: receber acesso ao domínio, configurar DNS, validar tudo.",
        ],
      },
      {
        id: "cria-responsabilidades",
        titulo: "9. Responsabilidades e o que NÃO fazer",
        conteudo: [
          "A Criação deve: receber e interpretar estratégia, transformar em checklist, montar PDF, enviar via WhatsApp, criar pasta Drive, cobrar envio, validar, produzir, revisar, subir no eKyte, programar social, liberar criativos, receber tickets, triar, escalar fora de contrato, estruturar sites, apresentar preview, apoiar publicação.",
          "A Criação NÃO deve: começar sem estratégia aprovada, pedir material de forma vaga, depender só do WhatsApp, aprovar fora do eKyte, executar ticket sem triagem, assumir demanda fora de contrato, subir site sem validação, deixar cliente sem prazo.",
          "Frase oficial: A Criação pega a estratégia aprovada, transforma em solicitação objetiva, produz as entregas visuais, conduz aprovação no eKyte, programa o social, libera criativos para Performance e finaliza o site até a publicação.",
        ],
      },
    ],
  },
  manual: {
    titulo: "Manual de Comunicação — Criação",
    subtitulo: "Scripts completos para cada momento da operação de Criação",
    blocos: [
      {
        id: "cria-b1",
        titulo: "Bloco 1 — Início do Fluxo de Criação",
        scripts: [
          {
            id: "cria-s1", numero: 1,
            titulo: "Primeiro contato da Criação após aprovação da estratégia",
            situacao: "A estratégia já foi apresentada e aprovada pela Performance. A Criação entra no fluxo.",
            objetivo: "Mostrar que a execução vai começar e que agora o cliente precisa colaborar com o envio dos materiais.",
            oQueClientePrecisaEntender: "Que os materiais pedidos fazem parte da estratégia aprovada e são importantes para transformar o plano em criativos reais.",
            scriptCurto: "Olá, [nome]. Agora que a estratégia foi aprovada, vou conduzir com você a parte de criação dos materiais. O próximo passo é o envio do checklist com os conteúdos que precisamos para começar a produção.",
            scriptCompleto: "Olá, [nome]. Tudo bem?\n\nAgora que a estratégia foi aprovada, vou conduzir com você a parte de criação dos materiais deste ciclo.\n\nA partir daqui, nosso foco é transformar o que foi planejado em conteúdos e criativos prontos para rodar, tanto no social quanto no tráfego, e também no site, quando isso fizer parte da sua estrutura.\n\nO próximo passo agora é o envio do checklist com os materiais que precisamos receber.",
            tomIdeal: "Seguro, didático, organizado.",
            erroAEvitar: "Soar como se a criação estivesse começando 'do zero', sem conexão com a estratégia.",
          },
          {
            id: "cria-s2", numero: 2,
            titulo: "Envio inicial do checklist de materiais",
            situacao: "Hora de pedir fotos, vídeos e outros materiais para produção.",
            objetivo: "Fazer o cliente entender o que precisa enviar e por que isso importa.",
            oQueClientePrecisaEntender: "Que o checklist não é burocracia. Ele é a base da produção do mês.",
            scriptCurto: "Estou te enviando o checklist dos materiais que precisamos para produzir os conteúdos e criativos deste ciclo.",
            scriptCompleto: "Olá, [nome].\n\nEstou te enviando o checklist com os materiais que precisamos para produzir os conteúdos e criativos deste ciclo.\n\nEsses materiais são importantes porque tudo o que vamos criar foi pensado em cima de uma estratégia.\n\nTe enviei:\n• o checklist em PDF\n• o link da pasta para subir os materiais\n• o prazo ideal de envio\n\nPrazo: [data]\n\nAssim que recebermos, seguimos para a produção.",
            tomIdeal: "Didático, claro, estratégico.",
            erroAEvitar: "Mandar o checklist sem explicar por que ele existe.",
          },
          {
            id: "cria-s3", numero: 3,
            titulo: "Envio do checklist no primeiro mês com tutorial",
            situacao: "Cliente está no começo da operação.",
            objetivo: "Educar o cliente para facilitar os próximos ciclos.",
            oQueClientePrecisaEntender: "Que o tutorial existe para tornar tudo mais fácil.",
            scriptCurto: "Como esse é o começo da operação, estou te enviando o checklist junto com o material de apoio de como gravar e como enviar os arquivos.",
            scriptCompleto: "Olá, [nome].\n\nComo esse é o começo da operação, estou te enviando:\n• o checklist dos materiais\n• a pasta para envio\n• o material de apoio de como gravar\n• e o material de apoio de como enviar\n\nA ideia é te deixar mais confortável nesse começo.\n\nPrazo de envio: [data]\n\nSe quiser, eu também posso te explicar os pontos mais importantes por aqui.",
            tomIdeal: "Acolhedor, simples, útil.",
            erroAEvitar: "Pressupor que o cliente já sabe gravar ou organizar os arquivos.",
          },
          {
            id: "cria-s4", numero: 4,
            titulo: "Explicando por que os materiais são importantes",
            situacao: "Cliente questiona ou não entende o pedido.",
            objetivo: "Mostrar valor estratégico dos materiais.",
            oQueClientePrecisaEntender: "Que o material ajuda a deixar o conteúdo mais forte, mais real e mais alinhado com venda e resultado.",
            scriptCurto: "Esses materiais são importantes porque a estratégia sozinha não gera resultado. A gente precisa transformar o plano em conteúdo real.",
            scriptCompleto: "Esses materiais são importantes porque a estratégia sozinha não gera resultado.\n\nA gente precisa transformar o que foi planejado em conteúdo real. E quanto mais o material tiver a ver com a sua empresa, mais forte tende a ficar a comunicação.\n\nNa prática, isso ajuda a:\n• passar mais verdade\n• chamar mais atenção\n• gerar mais conexão\n• melhorar os vídeos e anúncios\n• e deixar tudo mais alinhado com a venda\n\nNão é só para ficar bonito. É para ajudar a estratégia a funcionar melhor.",
            tomIdeal: "Didático, simples, convincente.",
            erroAEvitar: "Explicar só pelo lado estético ou só pelo lado do prazo.",
          },
          {
            id: "cria-s5", numero: 5,
            titulo: "Explicando por que existe prazo para envio",
            situacao: "Cliente não entende urgência.",
            objetivo: "Mostrar que o prazo protege a estratégia do mês.",
            oQueClientePrecisaEntender: "Que sem prazo a execução perde força e pode entrar atrasada.",
            scriptCurto: "O prazo é importante porque o que foi planejado para este mês precisa entrar no ar no tempo certo para gerar resultado.",
            scriptCompleto: "O prazo é importante porque o que foi planejado para este mês precisa entrar no ar no tempo certo.\n\nA gente trabalha com tudo organizado antes: produção, aprovação, programação e campanha. Quando o material entra no prazo, conseguimos executar melhor.\n\nQuando atrasa, a estratégia perde tempo de rodar.",
            tomIdeal: "Claro, estratégico, firme.",
            erroAEvitar: "Falar como se o prazo fosse só conveniência interna.",
          },
        ],
      },
      {
        id: "cria-b2",
        titulo: "Bloco 2 — Cobrança e Acompanhamento de Materiais",
        scripts: [
          {
            id: "cria-s6", numero: 6,
            titulo: "Primeiro lembrete de envio",
            situacao: "Cliente recebeu o checklist, mas ainda não enviou.",
            objetivo: "Reforçar sem parecer cobrança seca.",
            oQueClientePrecisaEntender: "Que a produção depende da entrada desse material.",
            scriptCurto: "Passando para reforçar o envio dos materiais do checklist. Eles são a base para conseguirmos produzir deste ciclo da forma certa.",
            scriptCompleto: "Olá, [nome]. Passando para reforçar o envio dos materiais do checklist.\n\nEles são a base para conseguirmos produzir os conteúdos e criativos deste ciclo da forma certa.\n\nPrazo combinado: [data]\n\nSe tiver dúvida sobre o que gravar ou enviar, pode me chamar que eu te ajudo.",
            tomIdeal: "Leve, organizado, prestativo.",
            erroAEvitar: "Cobrar sem abrir espaço para ajudar.",
          },
          {
            id: "cria-s7", numero: 7,
            titulo: "Segundo lembrete com mais contexto",
            situacao: "Cliente ainda não enviou.",
            objetivo: "Mostrar impacto do atraso sem gerar atrito.",
            oQueClientePrecisaEntender: "Que a falta do material começa a impactar a execução do plano.",
            scriptCurto: "Estou reforçando o envio dos materiais porque essa etapa é o que permite colocar a estratégia do mês em prática.",
            scriptCompleto: "Olá, [nome].\n\nEstou reforçando o envio dos materiais porque essa etapa é o que permite colocar a estratégia do mês em prática.\n\nSem esses arquivos, a gente não consegue produzir tudo da forma como foi pensado.\n\nSe conseguir enviar até [data], seguimos normalmente.",
            tomIdeal: "Firme, didático, estratégico.",
            erroAEvitar: "Ameaçar ou dramatizar o atraso.",
          },
          {
            id: "cria-s8", numero: 8,
            titulo: "Aviso de risco de atraso",
            situacao: "O prazo está estourando.",
            objetivo: "Formalizar o risco operacional.",
            oQueClientePrecisaEntender: "Que o envio fora do tempo ideal pode mexer no restante do ciclo.",
            scriptCurto: "Ainda não recebemos os materiais necessários para começar essa etapa da produção, e isso começa a impactar a execução.",
            scriptCompleto: "Olá, [nome].\n\nAinda não recebemos os materiais necessários.\n\nComo esses conteúdos fazem parte do que foi planejado para este mês, a falta do material começa a impactar a execução.\n\nSe o envio não acontecer até [data], pode ser necessário reajustar a sequência das entregas.\n\nAssim que recebermos, seguimos.",
            tomIdeal: "Profissional, claro, firme.",
            erroAEvitar: "Soar agressivo ou culpabilizador.",
          },
          {
            id: "cria-s9", numero: 9,
            titulo: "Quando o cliente envia só uma parte",
            situacao: "Material chegou incompleto.",
            objetivo: "Pedir complemento sem gerar confusão.",
            oQueClientePrecisaEntender: "Que ainda faltam itens para fechar a produção.",
            scriptCurto: "Recebi os materiais, obrigado. Já conferi e ainda faltam alguns itens para conseguirmos montar tudo da forma como foi planejado.",
            scriptCompleto: "Olá, [nome]. Recebi os materiais, obrigado.\n\nJá conferi por aqui e ainda faltam:\n• [item 1]\n• [item 2]\n• [item 3]\n\nEsses pontos são importantes para fechar melhor os conteúdos.\n\nSe puder me mandar isso até [data], seguimos com a produção completa.",
            tomIdeal: "Objetivo, claro, prático.",
            erroAEvitar: "Responder de forma vaga, sem listar exatamente o que falta.",
          },
          {
            id: "cria-s10", numero: 10,
            titulo: "Quando o material veio inadequado",
            situacao: "Arquivo está escuro, tremido, com ruído ou com baixa qualidade.",
            objetivo: "Pedir reenvio sem constranger.",
            oQueClientePrecisaEntender: "Que o ajuste melhora a força do material final.",
            scriptCurto: "Recebi os arquivos e alguns pontos podem atrapalhar a qualidade final da peça. Vou te pedir um ajuste ou reenvio de alguns itens.",
            scriptCompleto: "Olá, [nome]. Recebi os arquivos e conferi por aqui.\n\nAlguns materiais vieram com pontos que podem atrapalhar a qualidade final:\n• [item/problema]\n\nSe você reenviar desse jeito, conseguimos aproveitar melhor e entregar algo mais forte.",
            tomIdeal: "Cuidadoso, didático, respeitoso.",
            erroAEvitar: "Falar de forma dura ou crítica demais.",
          },
        ],
      },
      {
        id: "cria-b3",
        titulo: "Bloco 3 — Quando o Cliente Tem Dificuldade em Produzir",
        scripts: [
          {
            id: "cria-s12", numero: 12,
            titulo: "Quando o cliente diz \"não tenho material\"",
            situacao: "Cliente não tem fotos ou vídeos suficientes.",
            objetivo: "Não travar a operação.",
            oQueClientePrecisaEntender: "Que dá para priorizar o que é mais importante agora.",
            scriptCurto: "Sem problema. Vamos priorizar o que é mais importante para este ciclo e começar pelo que mais ajuda a estratégia a acontecer agora.",
            scriptCompleto: "Sem problema. Nesse caso, vamos priorizar o que é mais importante para este ciclo.\n\nNão precisamos começar com tudo. Precisamos começar com o que mais ajuda a estratégia a acontecer agora.\n\nPosso te orientar no mínimo necessário.",
            tomIdeal: "Empático, prático, resolutivo.",
            erroAEvitar: "Fazer o cliente se sentir culpado.",
          },
          {
            id: "cria-s13", numero: 13,
            titulo: "Quando o cliente diz \"não sei o que gravar\"",
            situacao: "Cliente está perdido.",
            objetivo: "Simplificar e tirar o peso da tarefa.",
            oQueClientePrecisaEntender: "Que ele não precisa inventar conteúdo sozinho.",
            scriptCurto: "Sem problema, isso é comum. Você não precisa pensar sozinho no que gravar. Posso te resumir os materiais mais importantes para este ciclo.",
            scriptCompleto: "Sem problema, isso é comum.\n\nVocê não precisa pensar sozinho. O mais importante é:\n• você falando de forma simples\n• imagens do ambiente\n• momentos do serviço\n• cenas do dia a dia\n• takes que mostrem credibilidade\n\nSe for melhor, eu posso te resumir os 3 ou 5 materiais mais importantes para gravar agora.",
            tomIdeal: "Acolhedor, simples, útil.",
            erroAEvitar: "Responder com mais complexidade ainda.",
          },
          {
            id: "cria-s14", numero: 14,
            titulo: "Quando o cliente acha que é muita coisa",
            situacao: "Resistência ao tamanho do checklist.",
            objetivo: "Mostrar que o pedido já foi organizado para facilitar.",
            oQueClientePrecisaEntender: "Que o checklist evita pedidos soltos durante o mês.",
            scriptCurto: "O checklist parece maior porque ele já foi montado para o ciclo todo. Isso evita que a gente fique te pedindo material toda hora.",
            scriptCompleto: "Entendo.\n\nO checklist parece maior porque ele já foi montado para o ciclo todo, e isso é até melhor para você.\n\nAssim evitamos ficar pedindo material toda hora e conseguimos produzir com mais consistência.\n\nSe quiser, eu posso separar o que é essencial agora e o que pode ficar como complemento.",
            tomIdeal: "Didático, leve, organizado.",
            erroAEvitar: "Responder como se o cliente estivesse exagerando.",
          },
        ],
      },
      {
        id: "cria-b4",
        titulo: "Bloco 4 — Quando a Criação Precisa Adaptar a Entrega",
        scripts: [
          {
            id: "cria-s18", numero: 18,
            titulo: "Quando o cliente enviou atrasado",
            situacao: "Material chegou fora do prazo.",
            objetivo: "Seguir com a operação, mas sinalizar impacto.",
            oQueClientePrecisaEntender: "Que o atraso pode mexer na ordem ou tempo de execução.",
            scriptCurto: "Recebi, obrigado. Vou seguir com a validação e encaixar a produção da melhor forma possível, mas o envio fora do prazo pode impactar a sequência.",
            scriptCompleto: "Recebi, obrigado.\n\nVou seguir com a validação e encaixar a produção da melhor forma possível. Só quero te alinhar que, como esse material entrou depois do prazo, isso pode impactar a sequência planejada.\n\nMesmo assim, vou organizar por aqui o melhor caminho.",
            tomIdeal: "Profissional, resolutivo, transparente.",
            erroAEvitar: "Responder de forma passivo-agressiva.",
          },
          {
            id: "cria-s19", numero: 19,
            titulo: "Quando o cliente não conseguiu enviar e vocês vão produzir mesmo assim",
            situacao: "Não houve material suficiente, mas vocês não querem travar a entrega.",
            objetivo: "Mostrar que a equipe resolveu, sem esconder a adaptação.",
            oQueClientePrecisaEntender: "Que a entrega foi mantida, mas fora do cenário ideal.",
            scriptCurto: "Como não conseguimos receber todos os materiais, seguimos com a produção usando o que tínhamos disponível e adaptando a execução.",
            scriptCompleto: "Olá, [nome].\n\nComo não conseguimos receber todos os materiais previstos, seguimos com a produção usando o que tínhamos disponível.\n\nSó quero te alinhar que essa versão foi construída sem parte dos materiais que tinham sido planejados. Então, ela pode ficar menos completa.",
            tomIdeal: "Transparente, resolutivo, maduro.",
            erroAEvitar: "Entregar adaptado sem explicar.",
          },
        ],
      },
      {
        id: "cria-b5",
        titulo: "Bloco 5 — Aprovação e Programação",
        scripts: [
          {
            id: "cria-s22", numero: 22,
            titulo: "Envio para aprovação no eKyte",
            situacao: "Materiais prontos.",
            objetivo: "Conduzir a aprovação com clareza.",
            oQueClientePrecisaEntender: "Que agora a validação dele libera a próxima etapa.",
            scriptCurto: "Os materiais deste ciclo já estão prontos e disponíveis no eKyte para sua aprovação.",
            scriptCompleto: "Olá, [nome].\n\nOs materiais deste ciclo já estão prontos e disponíveis no eKyte para sua aprovação.\n\nDepois da sua aprovação:\n• os conteúdos de social seguem para programação\n• os criativos de tráfego seguem para o time responsável\n\nSe puder, me dá esse retorno até [data].",
            tomIdeal: "Objetivo, organizado, claro.",
            erroAEvitar: "Pedir aprovação sem explicar o que acontece depois.",
          },
          {
            id: "cria-s23", numero: 23,
            titulo: "Aprovação pendente",
            situacao: "Cliente ainda não aprovou.",
            objetivo: "Reforçar a importância da validação.",
            oQueClientePrecisaEntender: "Que sem aprovação a estrutura não avança.",
            scriptCurto: "Passando para reforçar que os materiais enviados no eKyte ainda estão aguardando sua aprovação.",
            scriptCompleto: "Olá, [nome].\n\nPassando para reforçar que os materiais ainda estão aguardando sua aprovação.\n\nEsse retorno é importante para que a gente consiga seguir com a programação.\n\nSe houver qualquer ponto de ajuste, pode sinalizar por lá.",
            tomIdeal: "Calmo, firme, prático.",
            erroAEvitar: "Cobrar sem abrir espaço para ajuste.",
          },
          {
            id: "cria-s24", numero: 24,
            titulo: "Resposta a ajuste solicitado",
            situacao: "Cliente pediu correção.",
            objetivo: "Mostrar acolhimento e ação.",
            oQueClientePrecisaEntender: "Que o ajuste será feito e reenviado no fluxo correto.",
            scriptCurto: "Perfeito. Recebi seus pontos. Vou fazer os ajustes e subir a nova versão no eKyte para você validar novamente.",
            scriptCompleto: "Perfeito, [nome]. Recebi seus pontos.\n\nVou fazer os ajustes e subir a nova versão no eKyte para você validar novamente.",
            tomIdeal: "Objetivo, tranquilo, seguro.",
            erroAEvitar: "Justificar demais ou parecer incomodado com o ajuste.",
          },
          {
            id: "cria-s26", numero: 26,
            titulo: "Quando o cliente aprova",
            situacao: "Aprovação recebida.",
            objetivo: "Mostrar avanço claro do fluxo.",
            oQueClientePrecisaEntender: "Que a aprovação libera programação e campanhas.",
            scriptCurto: "Perfeito, aprovação recebida. Agora o que é social entra em programação e o que é tráfego segue para o time de performance.",
            scriptCompleto: "Perfeito, [nome]. Aprovação recebida.\n\nVou seguir agora com a próxima etapa:\n• conteúdos sociais → programação\n• criativos de tráfego → time de performance",
            tomIdeal: "Objetivo, positivo, seguro.",
            erroAEvitar: "Não explicar o que acontece depois da aprovação.",
          },
        ],
      },
      {
        id: "cria-b6",
        titulo: "Bloco 6 — Tickets e Pedidos Fora do Fluxo",
        scripts: [
          {
            id: "cria-s28", numero: 28,
            titulo: "Quando o cliente pede algo fora do fluxo no WhatsApp",
            situacao: "Cliente manda nova demanda pelo WhatsApp.",
            objetivo: "Trazer o pedido para o canal correto.",
            oQueClientePrecisaEntender: "Que o eKyte organiza, registra e protege o fluxo.",
            scriptCurto: "Para eu tratar isso da forma certa, peço que essa solicitação entre no eKyte como ticket.",
            scriptCompleto: "Perfeito, [nome].\n\nPara eu tratar isso da forma certa, peço que essa solicitação entre no eKyte como ticket.\n\nAssim conseguimos registrar, organizar e encaminhar corretamente.",
            tomIdeal: "Firme, educado, organizado.",
            erroAEvitar: "Resolver tudo pelo WhatsApp e perder rastreabilidade.",
          },
          {
            id: "cria-s29", numero: 29,
            titulo: "Ticket dentro do escopo",
            situacao: "Demanda extra entrou via eKyte e está dentro do fluxo.",
            objetivo: "Confirmar recebimento e andamento.",
            oQueClientePrecisaEntender: "Que o pedido foi visto e será tratado.",
            scriptCurto: "Recebi sua solicitação no eKyte e já coloquei esse ponto em andamento dentro do fluxo da criação.",
            scriptCompleto: "Olá, [nome].\n\nRecebi sua solicitação no eKyte e já coloquei esse ponto em andamento dentro do fluxo da criação.\n\nSe eu precisar de algo complementar, te aviso por lá mesmo.",
            tomIdeal: "Claro, seguro, organizado.",
            erroAEvitar: "Responder de forma vaga.",
          },
          {
            id: "cria-s31", numero: 31,
            titulo: "Ticket fora do contrato",
            situacao: "Pedido foge do escopo contratado.",
            objetivo: "Enquadrar sem atrito.",
            oQueClientePrecisaEntender: "Que isso precisa passar por triagem antes de execução.",
            scriptCurto: "Esse pedido foge do fluxo normal ou do escopo atual contratado, então vou deixar essa demanda em triagem e sinalizar o responsável comercial.",
            scriptCompleto: "Olá, [nome].\n\nRecebi sua solicitação e conferi por aqui.\n\nNeste caso, esse pedido foge do escopo atual contratado. Então vou deixar essa demanda em triagem e sinalizar o responsável comercial para alinhar o melhor caminho com você.\n\nAssim seguimos com clareza.",
            tomIdeal: "Profissional, firme, respeitoso.",
            erroAEvitar: "Executar direto ou recusar de forma seca.",
          },
        ],
      },
      {
        id: "cria-b7",
        titulo: "Bloco 7 — Site",
        scripts: [
          {
            id: "cria-s35", numero: 35,
            titulo: "Solicitação de materiais do site",
            situacao: "O escopo do site já foi montado e agora faltam materiais visuais.",
            objetivo: "Pedir o que falta para finalizar a página.",
            oQueClientePrecisaEntender: "Que esses materiais ajudam o site a ficar mais convincente.",
            scriptCurto: "A estrutura do seu site já está montada. Agora estamos na parte final, em que precisamos dos materiais visuais para deixar a página completa.",
            scriptCompleto: "Olá, [nome].\n\nA estrutura do seu site já está montada com base no que foi aprovado. Agora estamos na parte final.\n\nEstou te enviando:\n• o checklist dos materiais do site\n• a pasta para envio\n• o prazo ideal\n\nEsses materiais ajudam a deixar a página mais forte e mais alinhada com conversão.",
            tomIdeal: "Didático, claro, estratégico.",
            erroAEvitar: "Pedir material do site como se fosse só preenchimento visual.",
          },
          {
            id: "cria-s37", numero: 37,
            titulo: "Envio do preview do site",
            situacao: "Site pronto para validação.",
            objetivo: "Conduzir a aprovação da página.",
            oQueClientePrecisaEntender: "Que o foco é validar estrutura, clareza e conversão, não só gosto pessoal.",
            scriptCurto: "O site já está pronto nesta etapa e estou te enviando o link para você validar estrutura, textos, imagens, botões e experiência geral.",
            scriptCompleto: "Olá, [nome].\n\nO site já está pronto nesta etapa e estou te enviando o link para você validar.\n\nAqui o objetivo é você olhar a página funcionando e analisar:\n• estrutura\n• textos\n• imagens\n• botões\n• experiência geral\n\nO site foi construído pensando no papel dele dentro da estratégia.",
            tomIdeal: "Claro, organizado, estratégico.",
            erroAEvitar: "Pedir feedback genérico demais.",
          },
          {
            id: "cria-s40", numero: 40,
            titulo: "Confirmação antes de publicar o site",
            situacao: "Site já foi validado e falta publicar.",
            objetivo: "Alinhar acessos e passo final.",
            oQueClientePrecisaEntender: "Que agora é a etapa de colocar a página no ar.",
            scriptCurto: "Com a aprovação desta versão, podemos seguir para a publicação no domínio ou hospedagem final.",
            scriptCompleto: "Olá, [nome].\n\nCom a aprovação desta versão, podemos seguir para a publicação no domínio ou hospedagem final.\n\nAssim que os acessos estiverem confirmados, seguimos.",
            tomIdeal: "Objetivo, profissional, claro.",
            erroAEvitar: "Pressupor que o cliente já entende o que precisa enviar nessa etapa.",
          },
        ],
      },
      {
        id: "cria-b8",
        titulo: "Bloco 8 — Objeções e Cenários Sensíveis",
        scripts: [
          {
            id: "cria-s43", numero: 43,
            titulo: "Quando o cliente quer tudo muito rápido",
            situacao: "Cliente pressiona por velocidade.",
            objetivo: "Equilibrar rapidez e qualidade.",
            oQueClientePrecisaEntender: "Que a criação pode acelerar, mas sem perder coerência com a estratégia.",
            scriptCurto: "Nosso foco é te entregar com agilidade, mas sem perder a lógica do que foi planejado.",
            scriptCompleto: "Entendo a urgência.\n\nNosso foco é te entregar com agilidade, mas sem perder a lógica do que foi planejado. Quando a gente acelera sem base, a entrega tende a entrar mais fraca.\n\nVou organizar o melhor caminho para avançar com velocidade.",
            tomIdeal: "Calmo, firme, estratégico.",
            erroAEvitar: "Prometer velocidade sem olhar o impacto.",
          },
          {
            id: "cria-s45", numero: 45,
            titulo: "Quando o cliente quer peça muito diferente da estratégia",
            situacao: "Pedido foge da linha aprovada.",
            objetivo: "Mostrar que peça isolada pode enfraquecer o plano.",
            oQueClientePrecisaEntender: "Que a criação segue uma lógica, não só gosto.",
            scriptCurto: "Dá para avaliar, sim. Só preciso te sinalizar que essa ideia foge um pouco da linha que foi aprovada para este ciclo.",
            scriptCompleto: "Dá para avaliar, sim.\n\nSó preciso te sinalizar que essa ideia foge da linha aprovada. E como nossa criação segue uma lógica ligada à estratégia do mês, quando entra uma peça muito diferente, ela pode perder coerência.\n\nVou olhar esse ponto da forma correta e te retorno.",
            tomIdeal: "Calmo, estratégico, respeitoso.",
            erroAEvitar: "Rejeitar de forma seca ou aceitar sem olhar contexto.",
          },
          {
            id: "cria-s46", numero: 46,
            titulo: "Quando o cliente está inseguro com os materiais que enviou",
            situacao: "Cliente acha que não gravou bem ou que o material ficou ruim.",
            objetivo: "Reduzir ansiedade e manter o fluxo andando.",
            oQueClientePrecisaEntender: "Que vocês vão avaliar e orientar o que for necessário.",
            scriptCurto: "Fica tranquilo. Eu vou avaliar com calma e te sinalizo o que está bom para usar e o que vale ajustar.",
            scriptCompleto: "Fica tranquilo.\n\nEu vou avaliar com calma o que você enviou e te sinalizo o que está bom para usar, o que já resolve bem e o que vale ajustar.\n\nNem sempre precisa refazer tudo. Muitas vezes, com pequenos ajustes, já conseguimos usar muito melhor.",
            tomIdeal: "Acolhedor, confiante, leve.",
            erroAEvitar: "Aumentar a insegurança do cliente.",
          },
          {
            id: "cria-s47", numero: 47,
            titulo: "Regra principal da comunicação da Criação",
            situacao: "Aplicável a toda a cadeira.",
            objetivo: "Manter padrão de comunicação do time.",
            oQueClientePrecisaEntender: "Que a Criação não está só pedindo material ou fazendo arte; ela está executando uma parte importante da estratégia.",
            scriptCurto: "Nosso papel aqui é transformar a estratégia aprovada em materiais reais, claros e fortes, e te ajudar nesse processo do começo ao fim.",
            scriptCompleto: "A regra principal da comunicação da Criação é: falar de forma simples, explicar o porquê e sempre mostrar um caminho.\n\nOu seja, a Criação precisa sempre passar:\n• o que precisa ser feito\n• por que isso importa para o resultado\n• como vamos ajudar o cliente a fazer ou resolver\n\nA Criação conduz, simplifica, orienta, adapta quando necessário e mantém a entrega andando com o máximo de coerência com a estratégia.",
            tomIdeal: "Seguro, simples, resolutivo.",
            erroAEvitar: "Falar como executor visual sem conexão com a estratégia.",
          },
        ],
      },
    ],
  },
};
